version: '3.8'

services:
  # Frontend development server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    networks:
      - webpv-network

  # Backend API server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - APP_ENV=development
      - DEBUG=True
      - DATABASE_URL=postgresql://webpv:webpv123@db:5432/webpv
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000
    depends_on:
      - db
      - redis
    networks:
      - webpv-network

  # PostgreSQL database
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=webpv
      - POSTGRES_PASSWORD=webpv123
      - POSTGRES_DB=webpv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webpv-network

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webpv-network

volumes:
  postgres_data:
  redis_data:

networks:
  webpv-network:
    driver: bridge
