 
 
 DECLARE   @FECHA AS DATE,
 @S1 AS INT,
 @S2 AS INT,
 @S3 AS INT,
 @S4 AS INT,
 @RUTA AS INT;

 
SET @RUTA='001';
SET @FECHA='2025-09-01';
SET @S1=(SELECT DISTINCT SEMANA S1 FROM MBAFERGUEZ..R_Semanas WHERE  FECHA=@FECHA)
SET @S2=(SELECT DISTINCT SEMANA-1 S2 FROM MBAFERGUEZ..R_Semanas WHERE  FECHA=@FECHA)
SET @S3=(SELECT DISTINCT  SEMANA-2 S3 FROM MBAFERGUEZ..R_Semanas WHERE  FECHA=@FECHA)
SET @S4=(SELECT DISTINCT SEMANA-3 S4 FROM MBAFERGUEZ..R_Semanas WHERE  FECHA=@FECHA)
 
  

 
 SELECT  CTES.CLIENTE_ID,CTES.NOMBRE_CLIENTE,CTES.GECS,CTES.RUTA,RUTA_REP,VISITA,ENFRIADORES,OBJETIVOXSEMANA
	  ,CERVEZA_MANT,CERVEZA_MACT
	 ,CERVEZA_SANT3 ,CERVEZA_SANT2,CERVEZA_SANT,CERVEZA_SACT,CTECUMPLIDO
	  ,BRUME_SACT
      ,DESCLP,IDSHOP,VISITA,MILLER
	  ,INDIO,TECATE,INDIOM,XX 
	  
	  	 
		FROM(SELECT C.CLIENTE_ID,NOMBRE_CLIENTE,RUTA,RUTA_REP
		   ,CONVERT(VARCHAR,CASE WHEN  LUNES=1 THEN 'L'  ELSE '' END) + CONVERT(VARCHAR,CASE WHEN MARTES=1 THEN 'M'  ELSE '' END) + CONVERT(VARCHAR, CASE WHEN  MIERCOLES=1 THEN 'R'  ELSE '' END )	
		   + CONVERT(VARCHAR,CASE WHEN  JUEVES=1 THEN 'J'  ELSE '' END) + CONVERT(VARCHAR,CASE WHEN VIERNES=1 THEN 'V'  ELSE '' END )
		   + CONVERT(VARCHAR,CASE WHEN  SABADO=1 THEN 'S'  ELSE '' END) AS VISITA,GECS
			 FROM mbaFerguez..R_CLIENTES C
			 LEFT JOIN    R_VISITAS V ON C.CLIENTE_ID=V.CLIENTE_ID
	/******** ES EL DIA DE ACUERDO A LA FECHA SELECCIONADA*/
			where LUNES=1)CTES
		
			 /* VTA CER ANT $diaa*/
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) CERVEZA_MANT
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO='CERVEZA' AND MESVTA=MONTH(@FECHA)  AND ANIOVTA=YEAR(@FECHA)-1
				  GROUP  BY CLIENTE_ID)VANTC ON CTES.CLIENTE_ID=VANTC.CLIENTE_ID
		
			  /* VTA CER ACT */
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) CERVEZA_MACT
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO='CERVEZA' AND MESVTA=MONTH(@FECHA) AND ANIOVTA=YEAR(@FECHA)
				  GROUP  BY CLIENTE_ID)VACTC ON CTES.CLIENTE_ID=VACTC.CLIENTE_ID
			    
					 /* VTA CER ANT3 */
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) CERVEZA_SANT3
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO='CERVEZA' AND SEMANA=(SELECT DISTINCT SEMANA FROM MBAFERGUEZ..R_SEMANAS WHERE FECHA=@FECHA)-3  AND ANIOVTA=YEAR(@FECHA)
				  GROUP  BY CLIENTE_ID)VANTS3 ON CTES.CLIENTE_ID=VANTS3.CLIENTE_ID
				
				
				 /* VTA CER ANT2 */
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) CERVEZA_SANT2
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO='CERVEZA' AND SEMANA=(SELECT DISTINCT SEMANA FROM MBAFERGUEZ..R_SEMANAS WHERE FECHA=@FECHA)-2 AND ANIOVTA=YEAR(@FECHA)
				  GROUP  BY CLIENTE_ID)VANTS2 ON CTES.CLIENTE_ID=VANTS2.CLIENTE_ID
			
				 /* VTA CER ANT */
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) CERVEZA_SANT
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO='CERVEZA' AND SEMANA=(SELECT DISTINCT SEMANA FROM MBAFERGUEZ..R_SEMANAS WHERE FECHA=@FECHA)-1  AND ANIOVTA=YEAR(@FECHA)
				  GROUP  BY CLIENTE_ID)VANTS ON CTES.CLIENTE_ID=VANTS.CLIENTE_ID
		
			  /* VTA CER ACT */
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) CERVEZA_SACT
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO='CERVEZA' AND SEMANA=(SELECT DISTINCT SEMANA FROM MBAFERGUEZ..R_SEMANAS WHERE FECHA=@FECHA)  AND ANIOVTA=YEAR(@FECHA)
				  GROUP  BY CLIENTE_ID)VACTS ON CTES.CLIENTE_ID=VACTS.CLIENTE_ID
				
	  /* VTA BRU ACT */
		LEFT JOIN(SELECT CLIENTE_ID,SUM(CARTONES) BRUME_SACT
				  FROM mbaFerguez..vwVentasFerguez
				  WHERE GRUPO NOT IN ('CERVEZA','HIELO','PROMOCIONAL','PROMOCIONALES','VASO ENCERADO','ENVASE','PAQUETE') 
				  AND SEMANA=(SELECT DISTINCT SEMANA FROM MBAFERGUEZ..R_SEMANAS WHERE FECHA=@FECHA) AND ANIOVTA=YEAR(@FECHA) 
				  GROUP  BY CLIENTE_ID)BACTS ON CTES.CLIENTE_ID=BACTS.CLIENTE_ID
	
	
			/* ENFRIADORES */
		LEFT JOIN(SELECT * FROM MBAFERGUEZ..bdenf)ENFR ON CTES.CLIENTE_ID=ENFR.idCliente

		/*PROMO LONA*/
		
        LEFT JOIN(Select*,SUBSTRING(CLIENTECLAVE,3,6)ID, 'PROMLONA' AS DESCLP From dbGpoFernandez..ClienteEsquema where esquemaid='LPG008')LP ON CTES.CLIENTE_ID=LP.ID COLLATE Modern_Spanish_CI_AS
			
					   
LEFT JOIN(
select distinct CLIENTE_ID IDSHOP
from(
SELECT*
     FROM mbaFerguez..R_HEISHOP
UNION ALL
	 SELECT*
	 FROM (SELECT DISTINCT CLIENTE_ID
		   FROM MBAFERGUEZ..VWVENTASDETALLECAP
		   WHERE OBSERVACIONES LIKE '%HIP%' AND FECHAVTA>='2025-04-21')BD
WHERE   CLIENTE_ID NOT IN (SELECT*
								FROM mbaFerguez..R_HEISHOP)
union all
   SELECT clave
		   FROM MBAFERGUEZ..vwPreventaDetallea
		   WHERE FOLIO LIKE '%HI%' AND f_preventa>='2025-04-21')bd
					
								)HEI ON  CTES.CLIENTE_ID=HEI.IDSHOP 

left join (SELECT CLAVE=GECS+CONVERT(VARCHAR,SEMANA),BD.CLIENTE_ID,BD.NOMBRE_CLIENTE,BD.RUTA,BD.GECS,VTA,CASE WHEN BD.GECS='BRONCE' THEN 3  WHEN BD.GECS='PLATA' THEN 5
		   WHEN  BD.GECS='ORO' THEN 14 WHEN  BD.GECS='PLATINO' THEN 37  WHEN  BD.GECS='TITANIO' THEN 75   END OBJETIVOXSEMANA 
			, CASE WHEN  BD.GECS='BRONCE' THEN 2  WHEN BD.GECS='PLATA' THEN 3
		WHEN  BD.GECS='ORO' THEN 8 WHEN  BD.GECS='PLATINO' THEN  19 WHEN  BD.GECS='TITANIO' THEN 38 END CUMPLPAGO

		,SEMANA ,CASE WHEN VTA>=( CASE WHEN BD.GECS='BRONCE' THEN  3  WHEN BD.GECS='PLATA' THEN 5 
								  WHEN  BD.GECS='ORO' THEN 14  WHEN  BD.GECS='PLATINO' THEN  37 WHEN  BD.GECS='TITANIO' THEN 75  END 
								 ) THEN 1 ELSE 0 END  CTECUMPLIDO
		FROM (SELECT c.CLIENTE_ID,NOMBRE_CLIENTE,RUTA,CASE WHEN GECS IS NULL THEN 'BRONCE' ELSE GECS END GECS
			  ,CASE WHEN VTA<8 OR VTA IS NULL THEN 'COBRE' ELSE GECS END EVAGECS,VTA,SEMANA
		FROM MBAFERGUEZ..R_cLIENTES C
		LEFT JOIN(
		SELECT CLIENTE_ID,SUM(CARTONES)vTA,CASE WHEN SEMANA=@S4 THEN 1 WHEN SEMANA=@S3 THEN 2 WHEN SEMANA=@S2 THEN 3 WHEN SEMANA=@S1 THEN 4 END SEMANA
		FROM MBAFERGUEZ..vwVentasFerguez
		WHERE ANIOVTA=YEAR(@FECHA) AND GRUPO='CERVEZA' AND SEMANA IN (@S1)
		GROUP BY CLIENTE_ID,SEMANA)GN ON C.CLIENTE_ID=GN.CLIENTE_ID)BD)CUM ON  CTES.CLIENTE_ID=CUM.CLIENTE_ID
		
	LEFT JOIN (
	SELECT CLIENTE_ID,SUM(CARTONES) MILLER
	FROM MBAFERGUEZ..vwVentasFerguez V
	WHERE   GRUPO='CERVEZA' AND FECHAVTA BETWEEN '2025-09-01' AND  '2025-09-30'  AND MARCA='MILLER HIGH' 
  GROUP  BY  CLIENTE_ID,GECS
		  )ML  ON CTES.CLIENTE_ID=ML.CLIENTE_ID

LEFT JOIN (
		SELECT CLIENTE_ID, sum(cartones)INDIO
		  FROM MBAFERGUEZ..vwVentasFerguez V
		  WHERE   GRUPO='CERVEZA' AND FECHAVTA BETWEEN '2025-09-01' AND  '2025-09-30'  AND MARCA='INDIO' AND  CUPO='NR'
		  GROUP  BY  CLIENTE_ID,GECS
		  )IND  ON CTES.CLIENTE_ID=IND.CLIENTE_ID



LEFT JOIN (
		SELECT CLIENTE_ID, sum(cartones)INDIOM
		  FROM MBAFERGUEZ..vwVentasFerguez V
		  WHERE   GRUPO='CERVEZA' AND FECHAVTA BETWEEN '2025-09-01' AND  '2025-09-30'  AND MARCA='INDIO'
		  GROUP  BY  CLIENTE_ID,GECS
		  )INDM  ON CTES.CLIENTE_ID=INDM.CLIENTE_ID



LEFT JOIN (
		SELECT CLIENTE_ID, sum(cartones)TECATE
		  FROM MBAFERGUEZ..vwVentasFerguez V
		  WHERE   GRUPO='CERVEZA' AND FECHAVTA BETWEEN '2025-09-01' AND  '2025-09-30'  AND MARCA='TECATE' 
		  GROUP  BY  CLIENTE_ID,GECS
		  )TC  ON CTES.CLIENTE_ID=TC.CLIENTE_ID
		  
		  LEFT JOIN (
		SELECT CLIENTE_ID, sum(cartones)XX
		  FROM MBAFERGUEZ..vwVentasFerguez V
		  WHERE   GRUPO='CERVEZA' AND FECHAVTA BETWEEN '2025-09-01' AND  '2025-09-30'  AND MARCA='XX Lager' 
		  GROUP  BY  CLIENTE_ID,GECS
		  )XXL  ON CTES.CLIENTE_ID=XXL.CLIENTE_ID

 /***********CAMBIAR RUTA ******/
where CTES.ruta='001'